[General]
showlogo=shown
showClock=true
logo=/usr/share/sddm/themes/01-breeze-avisblue/default-logo.svg
type=image
color=#2A4A6E
fontSize=10
background=/usr/share/wallpapers/avisblue/contents/images/3840x2160.jxl
needsFullUserModel=false
